name: Java Compile and Run

on:
  push:
    branches:
      - main
    paths:
      - 'src/Main.java'
  workflow_dispatch:

jobs:
  build-and-run-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Main.java with specific encoding # 3. Main.java 컴파일 (인코딩 지정)
        run: |
          # 파일이 EUC-KR로 저장되었다고 가정하고 컴파일합니다.
          # 만약 CP949 (MS949)라면 -encoding CP949 로 변경하세요.
          javac -encoding EUC-KR src/Main.java
          ls src/ # 생성된 파일 확인

      - name: Run Main.class
        run: |
          java -cp src Main

      - name: Upload Main.class as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-java-class
          path: src/Main.class
          retention-days: 1